-- Create RESTAURANTS table
CREATE TABLE RESTAURANTS (
    RestaurantId VARCHAR2(10) PRIMARY KEY,
    RestaurantName VARCHAR2(50) NOT NULL,
    X NUMBER,
    Y NUMBER,
    Cuisine VARCHAR2(30),
    Username VARCHAR2(50) UNIQUE,
    Password VARCHAR2(50),
    Ratings NUMBER(3,2),
    TimesOrdered NUMBER,
    Offer NUMBER,
    MinAmount NUMBER
);

-- Create MENU_ITEMS table
CREATE TABLE MENU_ITEMS (
    ItemId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RestaurantId VARCHAR2(10) REFERENCES RESTAURANTS(RestaurantId),
    ItemName VARCHAR2(100) NOT NULL,
    Price NUMBER(8,2) NOT NULL,
    Category VARCHAR2(50),
    Description VARCHAR2(200)
);

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CustomerId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Phone VARCHAR2(15),
    Address VARCHAR2(200),
    Username VARCHAR2(50) UNIQUE,
    Password VARCHAR2(50)
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    OrderId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CustomerId NUMBER REFERENCES CUSTOMERS(CustomerId),
    RestaurantId VARCHAR2(10) REFERENCES RESTAURANTS(RestaurantId),
    OrderDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    TotalAmount NUMBER(10,2),
    Status VARCHAR2(20),
    DeliveryAddress VARCHAR2(200)
);

-- Create ORDER_ITEMS table
CREATE TABLE ORDER_ITEMS (
    OrderItemId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderId NUMBER REFERENCES ORDERS(OrderId),
    ItemId NUMBER REFERENCES MENU_ITEMS(ItemId),
    Quantity NUMBER,
    Price NUMBER(8,2)
);
